# build
[build]
  publish = "public"
  command = "gatsby build"
[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
# Headers 
[[headers]]
  for = "/static/*"
  [headers.values]
    cache-control = "public, max-age=360000"